hash-format = "sha256"

[[files]]
file = "config/MouseTweaks.cfg"
hash = "4069ce1a439d8c37453c1b1e9f2037e0942674c7e48723a39b37eab245792ad4"

[[files]]
file = "config/alltheheads-common.toml"
hash = "b5877430b97e89a55459c391e90ae66d293dfb9e996704fdec5d9368282d013c"

[[files]]
file = "config/armorposer.toml"
hash = "3d722c9b0301d7b8766ac9ee1aa5ca52ad3a46012185a1db2fe348aece6534d3"

[[files]]
file = "config/armorposer/User_poses.json"
hash = "4c344560b538644b857e90879ce372ed651844e9ff9f25416e3b3dcba8827320"

[[files]]
file = "config/betterclouds-v1.json"
hash = "21b3fccc5632999355c9cb7e77f10792753484d4c25e3384c8cf28e6a9475606"

[[files]]
file = "config/chat_heads.json5"
hash = "e198750061411cf7fca624e38b894ca104ca2cf2c2940da0409ce4240dcc2503"

[[files]]
file = "config/collective.json5"
hash = "b6243b955bf123f86c947510d9f8f3a4b5f7b8fe3775d834f458d60a3223847f"

[[files]]
file = "config/cubes-without-borders.json"
hash = "f248bc2019d956312c0c18037b84e764947dd200c00a96f45a807624d233010d"

[[files]]
file = "config/enchdesc.json"
hash = "7116b95a9b6797af8db84e410a2ca2fdf6f813461e37cd04bff5af933f31567b"

[[files]]
file = "config/entity_model_features.json"
hash = "881ed9c65f88bbf5d7c184fa6de2f85d7c5438dce99800f33969cb9673da1ef2"

[[files]]
file = "config/entity_texture_features.json"
hash = "0554c0e7816266477c65c18d2ada9fdddf1c6750787efd329056223ca4a073b2"

[[files]]
file = "config/etf_warnings.json"
hash = "a5ba22e63061c1fb67f0f895f17681351eaeccc225faef966c29ee630593275e"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "f0b32cd3444dcb92d1970e8594061c130e9314da05ea906272226aac475e1531"

[[files]]
file = "config/forgeconfigapiport.toml"
hash = "40dbe5b348f89b8ded62bcdfe32807ffc3e78fa8e0f81607a739580019fe5450"

[[files]]
file = "config/freecam.json5"
hash = "442d3c73c8d0c64a2445ef0c31b618db0034a2f452bf15751ec337287f34ef0c"

[[files]]
file = "config/horsestatsmod.json5"
hash = "5ebcc061fa85bf8e5c1a784ed0631c5509dbbdef458a9509b38673ed1ee45ee2"

[[files]]
file = "config/inventorysorter.json"
hash = "38b1e8492fb7d7e8da4ce3f426ae1c17bb0888b3df8b0b2fbd6aef449562a21f"

[[files]]
file = "config/journeymap-server.json"
hash = "2b77ff82093eb3698b79b2b953806855d1880d414544a8158f41b028d8e293ca"

[[files]]
file = "config/justmobheads.json5"
hash = "c5bcdc35b6c4fb7e5a96d552c10c13302c95956b3d6b038817cb97cd26f42801"

[[files]]
file = "config/justmobheads/headchances.txt"
hash = "97de20dc36b3a05af25e4f355b95de72fe2db330c5108439a31afefb77acde1f"

[[files]]
file = "config/justplayerheads.json5"
hash = "f1f888cb5f0da0d8c6dd2aaa866e15f4ceef00528d3602e24a2b7fef7d4b4dd0"

[[files]]
file = "config/justzoom/config.txt"
hash = "d0dcbc7c9c28a398ad2b81c1f6779f34beffbf45560c8c02c063077ab32ded45"

[[files]]
file = "config/lambdynlights.toml"
hash = "fdd6958ff17541c8d1c891bd1602088bb6888f41229e966387a07311f32ec6d9"

[[files]]
file = "config/litematica.json"
hash = "1178b510a0bb2165ad6655a9c8a7a62e8aa6b627ed5cd33f46d508d9177159a2"

[[files]]
file = "config/litematica/area_selections_per_world/MIS V5/area_selections/Storage.json"
hash = "849f9fce92f4a302e24ed86f7852db51e8b9db5487580fd2c883ebda35c76505"

[[files]]
file = "config/litematica/litematica_MIS V5.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_MIS V5_dim_minecraft_overworld.json"
hash = "11091941d2a64fa6d6e19915052922fd9a1fef627db894c44f6bddc4d1563de2"

[[files]]
file = "config/litematica/litematica_New World.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_New World_dim_minecraft_overworld.json"
hash = "adcadb841e38244e0121845e5c11366cb7fca48d1e6518db75eb8369eb9cc582"

[[files]]
file = "config/litematica/litematica_NoisyMIS.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_NoisyMIS_dim_minecraft_overworld.json"
hash = "6d1c1ed777aee68d3ec97619bf6991803f32b5a80fad8dcd4aac585e7dc3c891"

[[files]]
file = "config/litematica/litematica_vanilla.kgb33.dev.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_vanilla.kgb33.dev_dim_minecraft_overworld.json"
hash = "778ae6ee92f31a6e8b9317c19dd990ea41a6a697a9ad97b9024ca6b1579368dd"

[[files]]
file = "config/litematica/litematica_vanilla.kgb33.dev_dim_minecraft_the_end.json"
hash = "5d05ef89104d6fe2085ed7906b74584fd6a3aa01abbe7df7f5aa7a84146919fc"

[[files]]
file = "config/litematica/litematica_vanilla.kgb33.dev_dim_minecraft_the_nether.json"
hash = "adcadb841e38244e0121845e5c11366cb7fca48d1e6518db75eb8369eb9cc582"

[[files]]
file = "config/litematica/raw_material_list_recipe_details_2025-11-10_15.28.58.json"
hash = "0ca78852146ac2c3a1ac832b418be48f2432033c8181d2c1bfa1c48c5df77915"

[[files]]
file = "config/litematica/raw_material_list_recipe_steps_2025-11-10_15.28.58.json"
hash = "b8939fa724f2b4eda064f0e610a56bb0c2ab5c677ffca5d38fcd28e6547d87d2"

[[files]]
file = "config/litematica/raw_material_list_simplified_2025-11-10_15.28.58.json"
hash = "2b149417fd2b5c05c91e5ae66faec0722d1bb3d3af34f042bf27f6afd987a282"

[[files]]
file = "config/locator-heads.json"
hash = "dd07c3b60c50b02cab3287df914f7127e4edd1decbc2d16ebb65fe7a9e512c6c"

[[files]]
file = "config/lootr.json"
hash = "1c0fbe0965bdfb1271b7be90e86bc4fbd9114bb768fc0a4995da0f3621531bfc"

[[files]]
file = "config/malilib.json"
hash = "85ca79ccc1896ec7168d0b61a4eca8ebfcbd096f46c37df07211952fa2d6f470"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/particlerain.json"
hash = "417f2b20e1243a1ec2f8bea4e558f43b66182f446ecdb3f29a33b015b882f752"

[[files]]
file = "config/polymer/auto-host.json"
hash = "26ab57411745916fa6bf5f54b0df43dda04e3b6d379a5b3fdec94ad6d56f2382"

[[files]]
file = "config/polymer/client.json"
hash = "d8a4e36c8c4df8c5612aa9485d6a2e7a43cb2aa7f1584a52bb6373d6c94037c4"

[[files]]
file = "config/polymer/common.json"
hash = "310dee45deffb1f13169492bf25cee00503e91403daa8cffa653939feb76cc03"

[[files]]
file = "config/polymer/resource-pack.json"
hash = "7a4243c13c9606c7cc046ae66f36979b87bd7924baef657dbb577cb4375c2e95"

[[files]]
file = "config/polymer/server.json"
hash = "eaec27618070f4daf636a5e8457c978e1d9afffa22fba907eca29cdd700a94d2"

[[files]]
file = "config/polymer/sound-patch.json"
hash = "f815116c7a6a7ba28de432cf2be7fdbf49e2e1adb5436438d347d391ee3b5c74"

[[files]]
file = "config/shulkerdropstwo.json5"
hash = "c51a8d28d4e34f2fa558cb57aef6e8c023a501c11e2eadf7e4aafdfa8b1032d0"

[[files]]
file = "config/simple_harvesting.json"
hash = "59b04156dcbdfb7c4ebf99c3467a67f6c978af45e99d93ea4e515f36faa0b52f"

[[files]]
file = "config/skinlayers.json"
hash = "980b9889cf6a14d2df8cd14c269b307b48743afeadaa38d14395f1c8d9e874db"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "bca02fec42be5a3794055eee644bd895e21c9a66004343ed60965f45338ef472"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "0c34e9630f481e6af9dac31ca068ff3ec95f761d95b4385ff52d20d24b8f4411"

[[files]]
file = "config/trade_cycling/trade_cycling.properties"
hash = "5610bec5a681bd00da2bd273f7eadc1cc03864b1059461860b8ece325db9341d"

[[files]]
file = "config/transition.json"
hash = "6c0060c7301372bbc414f86a139b383e34fb620f0621badd71bb19efc3f26767"

[[files]]
file = "config/trender.json"
hash = "0a282f3623f7f9443a1d10b5768865f69e58b74e000dcfb4f40399626b7a6124"

[[files]]
file = "config/universal-graves/config.json"
hash = "e5de99ef8cf0b47ade7d9248385778d33bdecae381fc4ee246d2c54749c7d81a"

[[files]]
file = "config/universal-graves/example_models/corpse_player.json"
hash = "f1f86bd740c9bde120cca8769e900005cf46f67cfb076b65b50c339f47deb69e"

[[files]]
file = "config/universal-graves/example_models/corpse_zombie.json"
hash = "dc1ee62c77ef7831f52c1c9a44c5dff3e5ccaa4094d43438e9fdbe1f41a06a17"

[[files]]
file = "config/universal-graves/example_models/default.json"
hash = "c0f6c5e52fcfe066b1b300e9c4c738feb87dc1397ce45e58b99b63cb25e07167"

[[files]]
file = "config/universal-graves/example_models/ender.json"
hash = "87be637b2b08c7f97550362d66f1682ce475c4c29a470f96a44cdf86f6dc6c0e"

[[files]]
file = "config/universal-graves/example_models/player_head.json"
hash = "c0f6c5e52fcfe066b1b300e9c4c738feb87dc1397ce45e58b99b63cb25e07167"

[[files]]
file = "config/universal-graves/example_models/soul.json"
hash = "bd3c7cba512978e4d0f5632aed773b47d93e80e9243656fc092d6cc56ddc53e1"

[[files]]
file = "config/visuality.json"
hash = "1561b99ae57ede995dfb64a91ac5b53dd877f57e4a8f1859526da84511bcec07"

[[files]]
file = "config/voicechat/category-volumes.properties"
hash = "94c1c4f70e5b995fbd71e86d4fa646030437fecae0685875b560a55fbd0d0e56"

[[files]]
file = "config/voicechat/player-volumes.properties"
hash = "d7a32c122de86a6341dbb783cd5205e84a0718d1a08b1d73320db881803f1316"

[[files]]
file = "config/voicechat/translations.properties"
hash = "693643b1d393cbb3ea7f062afc4474fcd66e4036c4f8d7c056434979cbf512d1"

[[files]]
file = "config/voicechat/username-cache.json"
hash = "7835881976d35e76646df2b23436fdfa947f95127858f479369a3ced1a82b584"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "4a047e6e348e536dda78fbf8d70c7d7aea988d9a3e7385556facbd45f28de2e6"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "230cf5d9bc8b2f115732210068adbfacb70fb50708f09d4dfe0baccac8cef336"

[[files]]
file = "config/voxy-config.json"
hash = "c8b5bcb25a84ef51aa4e06ed19c4fa8317ca71fffcc4cf9549901416006973b4"

[[files]]
file = "config/yacl.json5"
hash = "121b93764159be6fb7dab523b29a844e2bb78400ce8c48f52135a097e9b0006e"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "cb70174b0daa4c90b5b573e8043bc06381355e3bb7c337394f4e324a8918fa40"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "a5d332d97f29c1f3b2ca274d9076169e11e71fa6b42f65536004a1d830a37727"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "01a476eda8e70ae3609ba2ee5bcaa0530e6f9f7cdb6783b263c0a1b4b88de070"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "bc62c653a8b1a5eb0af7ce374430e9000bd999f4d5afb82e875d21fc13c11abd"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "d9bb477a944c92ae2f95d812f5344bdae01bf2f81b305bddabc090f72f3f63c6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "1f74b5e976f9ccf2ed7c4e200d1c180555b762589ab727bc5eea5c017d6c5fa9"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "af558a7155aec0644028cdc65fa58c056a3863f06f1046c6f82c0ab5cfb94df1"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "cd9a77c839078e91469f7f02ab902f5eee2691a0de041cf1f1fe22a24b0741f8"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "614b19c6566fb1f22193b98b57b6172d2b7e1213e93b73692491dbca023211e2"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "38ab0b734ed6dd3ce49fab69b4d66793a3a459a321a9c94897695e829cac6681"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "39b4f43a271700276ff1ae632cf05f90b85f79670d955b50ced036e363a0efe9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b898e0d94915287fcce4f85a3e5135e831475957e03d035ac05ecd7a7585929d"
metafile = true

[[files]]
file = "mods/free-cam.pw.toml"
hash = "a06b32e36fa856b6137255a003153d4940f2d54f377b4109b7a18c5cb2190146"
metafile = true

[[files]]
file = "mods/horse-statistics.pw.toml"
hash = "d4e385a049db12e5b8c9c4f4cd839c68c2540cf3b2e66086330fa690ea96fec2"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "44d15f997bad929d2e8344015701a065c1ed08d930656f11dd7ed3386668b070"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "fa37926328b6b605cce3ca966e2b50af973a2d1043188da4599f105c2a430606"
metafile = true

[[files]]
file = "mods/just-mob-heads.pw.toml"
hash = "75c9ff4f2ba5247c7d6a9c02f1371fe7d9994972910240f0e7aa780e05701ea7"
metafile = true

[[files]]
file = "mods/just-player-heads.pw.toml"
hash = "e18f5d8d880468af8178b5fb3534231a32a0068a5b0998f890515e751500b453"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "dfe8fb2ac2eacdc0b406fc27e6f5750f77c2e16993137b5d2f54b710fa7a1b7d"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "ec7dc6f7a704b1db636a03f2a3f672c8d0af0eddb7d4ef2f209f292a425b2dc8"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "ff9af33704ca388bc255fa78515231e2a5c68c0be85cb86e68a764aa8768ef13"
metafile = true

[[files]]
file = "mods/litematica-update-port.pw.toml"
hash = "f7a2502f7cb40cbe653f42bf73b9e1245b05fbdb0519411fdb2218d5c6ee17ba"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
hash = "3dae24b3d4a5d4a99b5cf5629d5df236e128fddaef9c6202a19f0136769a1bb2"
metafile = true

[[files]]
file = "mods/lootr-fabric.pw.toml"
hash = "350a1391ffb187face0ddba6f5ec26df4bfd681c1c45adb2d05a840d1ece846e"
metafile = true

[[files]]
file = "mods/malilib-update-port.pw.toml"
hash = "aa607ff2873f8165a7bd9c8d28976aebb578402d08ea73ae62c5d5cd7cf36b50"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "037f48cc503913e20d60a198fe1d6b40953e32cfb0fdff45361bbf1cdf6708ad"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "c68301b49d033b58dd3a9ccfdd781bda6fac0609ea6a426b2adb57efacc860ac"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "2c12b667ab0051eaebcecff752242bdccbb33b7c87c6bd983a98ab67b7f5fedd"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "0a2e7468423d5636822b43707043e48f57e749f9382def85060e6f27f74aa8a5"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "b66c4319ea2b1856d3e7d19bf18d8a8445040a3125dd75c193834d651d6f7335"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "7745c6e05de772a441306fc08dd5299ce4480e39d2d27addf4fd71ae5b66c4e9"
metafile = true

[[files]]
file = "mods/rounds-invisible-frames.pw.toml"
hash = "943f8a5db0799a89fba3b468888ca8993639f221c096d23471c4878bba34693c"
metafile = true

[[files]]
file = "mods/shulker-drops-two.pw.toml"
hash = "02fd25fcddb9c11ca93160163863b1ff6e0f824fb3d2e2c4c16f3b8d64b3bca1"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "11db2f1acc702cfc92d43efd8800b4b9db54e3c059ec1d35754618adacffc334"
metafile = true

[[files]]
file = "mods/simple-harvesting.pw.toml"
hash = "01ec2c52a3134a54d034afc8172c33a34421636a72868f305b3b9aa305d5e198"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "756081c3965727c88a843949ad5b9758af3e677d31ad2dcbd53d4bdea61720de"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "e8338121752473aee4681eede26c3eac75bf6ff5bfd1a0d43a1848b491a4c7a6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "f8e1d7d95c5c2b723fa2c4e16deedc0bbeb4326e322fac2aa616e1619ffa07d3"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c5fdf842ac50d5992853c9c6f073d876d358913b161498eb2f52b1de58d2a390"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "49894ff88d08a8af582886235f9e784e78d3f00f6b1ed41098e8789123317433"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "2fb7277fb158fe6418cd861086c7e35d0061a13a576a16ecd84c0c80286ff415"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "c2680d0e800fbb22cf8a001151c79b8163eca541eb7b7ba10251108d7e051ebb"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
hash = "eccf0403881be365c1b79457210ddd0c07f605155c87d07a40739e06c537dd7e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "eb9876fa0317ffa09fe9df3b615d3567086830c1274e2856c73c533717d53fae"
metafile = true

[[files]]
file = "options.txt"
hash = "51a1728e38f540611478077ca6acd35bf58728332b6fcf09ffebc2a1991b3098"

[[files]]
file = "servers.dat"
hash = "aa165abb739f6a00d888b753d081dfe3c9d9fd90657ef71039486d5a0e77114d"
